### ISSUE TITLE
[MIXIN] InjectionError on game load

### ISSUE THREAD

**Issue by Klouver-github** [infernalexp/Greed-Bleed#3]
I added Greed And Bleed alpha 1 to my mod folder and it crashed my loading screen

https://paste.gg/p/anonymous/89a6d10ca1404c3e80e23eab504db5dd

**Comment by dvitski** [comment]
`Redirect` incompatibility with `sapience`

**Comment by Klouver-github** [comment]
You monsters!

**Comment by dvitski** [comment]
[build](https://cdn.discordapp.com/attachments/716876957513678950/880587065505501184/greedandbleed-0.1.0-sapience1.16.5-forge.jar)

![image](https://user-images.githubusercontent.com/36608902/131046683-a8417c6d-6ed0-4926-98ac-4831dbd10001.png)

**Comment by Klouver-github** [comment]
I am giving you my trust one last time Andante
this

**Comment by Klouver-github** [comment]
https://paste.gg/p/anonymous/58a69b60ca5f48d782323b27835173e9
you hurt my feels

**Comment by dvitski** [comment]
I despise Forge.

**Comment by Klouver-github** [comment]
not sure to agree or be hurt

**Comment by TinyAtomss** [comment]
both

**Comment by Klouver-github** [comment]
ur right

**Comment by dabomb6405** [comment]
Having this same issue.

**Comment by Klouver-github** [comment]
we shall rage

**Comment by Klouver-github** [comment]
where the update bro? I am fixing to angry sandwich like Bugsnax raiding the people

**Comment by Klouver-github** [comment]
WHERE's THE UPDATE MY GUY?! I Have been sitting here for 3 years waiting but No I try contacting the manager and company as well but not even they answered to my calls, I feel so outraged to this un-supervised Mod that should give me hog rider

**Comment by JonahFuses** [comment]
WE ARE VERY SORRY FOR THE INCONVENIENCE

**Comment by Klouver-github** [comment]
SORRY IS TO LATE!!! I AM REPORTING THIS TO FBI AND MOJANG!!
